name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Lowercase Repository Name
        run: |
          echo "LOWER_REPOITORY_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image (All Targets)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: csenv
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_REPOITORY_NAME }}/csenv:latest
          cache-from: type=gha

      - name: csenv-for-test-litespeed-general
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-test-litespeed-general
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_REPOITORY_NAME }}/csenv-for-test-litespeed-general:latest
          cache-from: type=gha

      - name: csenv-for-test-litespeed-circleci
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-test-litespeed-circleci
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_REPOITORY_NAME }}/csenv-for-test-litespeed-circleci:latest
          cache-from: type=gha

      - name: csenv-for-test-apache-general
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-test-apache-general
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_REPOITORY_NAME }}/csenv-for-test-apache-general:latest
          cache-from: type=gha
