name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [chrome-update]
  workflow_dispatch:

jobs:
  csenv:
    name: Build and Push csenv:latest (csenv)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv:latest
          cache-from: type=gha
          cache-to: type=gha

  base_csenv-for-test:
    name: Base Image Build (base_csenv-for-test)
    needs: csenv
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: base_csenv-for-test
          push: false
          cache-from: type=gha
          cache-to: type=gha

  base_csenv-for-test-litespeed:
    name: Base Image Build (base_csenv-for-test-litespeed)
    needs: base_csenv-for-test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: base_csenv-for-test-litespeed
          push: false
          cache-from: type=gha
          cache-to: type=gha

  csenv-for-test-litespeed-general:
    name: Build and Push csenv:test-litespeed-general-latest (csenv-for-test-litespeed-general)
    needs: base_csenv-for-test-litespeed
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-test-litespeed-general
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv:test-litespeed-general-latest
          cache-from: type=gha

  csenv-for-test-litespeed-circleci:
    name: Build and Push csenv:test-litespeed-circleci-latest (csenv-for-test-litespeed-circleci)
    needs: base_csenv-for-test-litespeed
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-test-litespeed-circleci
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv:test-litespeed-circleci-latest
          cache-from: type=gha

  base_csenv-for-test-apache:
    name: Base Image Build (base_csenv-for-test-apache)
    needs: base_csenv-for-test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: base_csenv-for-test-apache
          push: false
          cache-from: type=gha
          cache-to: type=gha

  csenv-for-test-apache-general:
    name: Build and Push csenv:test-apache-general-latest (csenv-for-test-apache-general)
    needs: base_csenv-for-test-apache
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-test-apache-general
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv:test-apache-general-latest
          cache-from: type=gha

  csenv-for-test-apache-circleci:
    name: Build and Push csenv:test-apache-circleci-latest (csenv-for-test-apache-circleci)
    needs: base_csenv-for-test-apache
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-test-apache-circleci
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv:test-apache-circleci-latest
          cache-from: type=gha
